// src/apps/customer-portal/src/components/ErrorBoundary.tsx
import { Component, type ErrorInfo, type ReactNode } from 'react';

import { t } from '../i18n';
import { trackEvent } from '../telemetry';

type Props = { children: ReactNode };
type State = { hasError: boolean };

export class ErrorBoundary extends Component<Props, State> {
  state: State = { hasError: false };

  static getDerivedStateFromError(): State {
    return { hasError: true };
  }

  componentDidCatch(error: Error, info: ErrorInfo): void {
    trackEvent('portal.error.boundary', { message: error.message, componentStack: info.componentStack ?? '' });
  }

  render() {
    if (this.state.hasError) {
      return (
        <section role="alert" className="panel error-panel">
          <h1>{t('error.boundary')}</h1>
          <p>{t('error.sessionExpired')}</p>
        </section>
      );
    }
    return this.props.children;
  }
}

// src/apps/customer-portal/src/components/ErrorBoundary.vue
<script setup>
import { onErrorCaptured, ref } from 'vue';

import { t } from '../i18n';
import { trackEvent } from '../telemetry';

const hasError = ref(false);

onErrorCaptured((error, _instance, info) => {
  hasError.value = true;
  const message = error instanceof Error ? error.message : String(error);
  trackEvent('portal.error.boundary', { message, componentStack: info });
  return false;
});
</script>

<template>
  <section v-if="hasError" role="alert" class="panel error-panel">
    <h1>{{ t('error.boundary') }}</h1>
    <p>{{ t('error.sessionExpired') }}</p>
  </section>
  <slot v-else />
</template>
