// src/apps/customer-portal/src/components/WorkspaceSwitcher.vue
<script setup>
import { useSession } from '../auth/session';
import { t } from '../i18n';
import { trackEvent } from '../telemetry';

const session = useSession();

function onWorkspaceChange(event) {
  const next = event.target.value;
  trackEvent('portal.workspace.switch', { workspaceId: next });
  void session.switchWorkspace(next);
}
</script>

<template>
  <label v-if="session.workspaces.length > 0" class="workspace-switcher">
    <span class="visually-hidden">{{ t('workspace.switch') }}</span>
    <select
      :aria-label="t('workspace.switch')"
      :value="session.workspaceId ?? ''"
      @change="onWorkspaceChange"
    >
      <option v-for="workspace in session.workspaces" :key="workspace.id" :value="workspace.id">
        {{ workspace.name }}
      </option>
    </select>
  </label>
</template>

// src/apps/customer-portal/src/components/WorkspaceSwitcher.tsx
import { useSession } from '../auth/session';
import { t } from '../i18n';
import { trackEvent } from '../telemetry';

export function WorkspaceSwitcher() {
  const { workspaces, workspaceId, switchWorkspace } = useSession();
  if (workspaces.length === 0) {
    return null;
  }

  return (
    <label className="workspace-switcher">
      <span className="visually-hidden">{t('workspace.switch')}</span>
      <select
        aria-label={t('workspace.switch')}
        value={workspaceId ?? ''}
        onChange={(event) => {
          const next = event.target.value;
          trackEvent('portal.workspace.switch', { workspaceId: next });
          void switchWorkspace(next);
        }}
      >
        {workspaces.map((workspace) => (
          <option key={workspace.id} value={workspace.id}>
            {workspace.name}
          </option>
        ))}
      </select>
    </label>
  );
}
